# File: .github/workflows/deploy-angular.yml
name: Deploy Angular to GitHub Pages

on:
  push:
    branches:
      - main  # Trigger on push to main

jobs:
  build-and-deploy:
    name: Build Angular and Deploy
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Use Node.js
      uses: actions/setup-node@v3
      with:
        node-version: 20

    - name: Install dependencies
      working-directory: Angular
      run: npm ci

    - name: Build Angular app
      working-directory: Angular
      run: npx ng build --configuration production --base-href "/BankStatementPDFToExcel/"

    - name: Set Git user
      run: |
        git config --global user.email "afiqwazien.nawawi@gmail.com"
        git config --global user.name "afiqwazien"

    - name: Deploy to GitHub Pages
      working-directory: Angular
      run: npx angular-cli-ghpages --dir=dist/browser --no-silent
      env:
        GH_TOKEN: ${{ secrets.GH_PAT }}
